apiVersion: batch/v1
kind: CronJob
metadata:
  name: total-calculator-cron
  namespace: bohdansavshak
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: total-calculator-cron
              image: lari245/first-promotion-image:latest
              imagePullPolicy: Always
              # Add any required args here
              env:
                - name: APP
                  value: total-calculator
          imagePullSecrets:
            - name: promotion
          restartPolicy: OnFailure