spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ${client_id}
            client-secret: ${client_secret}
            authorization-grant-type: client_credentials
            scope: message
        provider:
          okta:
            token-uri: https://mylogin.bohdansavshak.com/oauth2/ausd8lbvukyE7vBEM5d7/v1/token
server:
  port: 9191